# Generated by Django 4.2.10 on 2024-02-16 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=40, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=40, unique=True)),
                ('phone_number', models.CharField(max_length=17)),
                ('name', models.TextField(max_length=30)),
                ('surname', models.TextField(max_length=30)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('age', models.PositiveSmallIntegerField()),
                ('height', models.PositiveSmallIntegerField()),
                ('weight', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
