# Generated by Django 4.2.11 on 2024-03-08 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='special_types',
            field=models.ManyToManyField(to='core.special_types'),
        ),
    ]
