# Generated by Django 4.2.11 on 2024-03-08 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_categories_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='estimated_time',
            new_name='cooking_time',
        ),
        migrations.AddField(
            model_name='recipe',
            name='prep_time',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
