# Generated by Django 4.2.11 on 2024-05-05 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_aboutus_status_alter_aboutus_header_main_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('fullname', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=128, unique=True)),
                ('subject', models.TextField(max_length=300)),
                ('content', models.TextField(max_length=3000)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
    ]
