# Generated by Django 4.2.11 on 2024-05-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_recipe_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('email', models.EmailField(max_length=128, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='dietprogram',
            name='name',
            field=models.CharField(default='abc', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='chef_choice',
            field=models.CharField(choices=[('active', 'Active'), ('passive', 'Passive')], default='passive'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='chef_popular',
            field=models.CharField(choices=[('active', 'Active'), ('passive', 'Passive')], default='passive'),
        ),
        migrations.AlterField(
            model_name='dietprogram',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('share', 'Share')], default='draft', max_length=40),
        ),
        migrations.AlterField(
            model_name='dietprogramitem',
            name='day',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')]),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='status',
            field=models.IntegerField(choices=[('1', 'Active'), ('0', 'Deactive')], default=1),
        ),
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='status',
            field=models.IntegerField(choices=[('1', 'Active'), ('0', 'Deactive')], default=1),
        ),
    ]
